version: '3.7'

services:
  mysql:
    container_name: rs-lokalise-test-sql-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: rs-lokalise-test-sql-php
    volumes:
      - .:/srv/app
    networks:
      - app-network
    depends_on:
      - mysql

volumes:
  mysql-volume:

networks:
  app-network:
